########################################################################
# Copyright (c) 1988-2016 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 6/29/2016
#
# Gcc Makefile for evup
########################################################################

EVUP_SRC = $(PKG)/$(SRC)

#
# user includes
#
evup_USRINCLUDES += \
-I${EVUP_SRC}/os/evup \
-I${EVUP_SRC}/os \
-I${EVUP_SRC}/file \
-I${EVUP_SRC}/evup \
-I${EVUP_SRC}/base \
-I${EVUP_SRC} \

#
# user defines
#
evup_USRDEFINES += \

#
# user c++ flags
#
evup_USRCXXFLAGS += \

#
# user c flags
#
evup_USRCFLAGS += \

#
# user ld flags
#
evup_USRLDFLAGS += \

#
# user libdirs
#
evup_USRLIBDIRS += \

#
# libs
#
#LIBS = \
#-lsomelib
#
evup_LIBS += \
-lev \

#
# depend
#
#DEP = \
#$(PKG)/$(BLD)/libsomelib \
#
evup_DEP += \

#
# depend dirs
#
#DEP_DIRS = \
#../libsomelib
#
evup_DEP_DIRS += \


