########################################################################
# Copyright (c) 1988-2017 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 12/13/2017
#
# generic Gcc Makefile for xde Executable cxxlcgi
########################################################################


#
# target
#
cxxlcgi_EXETARGET = xde-cxxlcgi

########################################################################

#
# user c++ flags
#
cxxlcgi_USRCXXFLAGS += \
${xde_USRCXXFLAGS} \

#
# user defines
#
cxxlcgi_USRDEFINES += \
${xde_USRDEFINES} \

#
# user includes
#
cxxlcgi_USRINCLUDES += \
${xde_USRINCLUDES} \

#
# user libdirs
#
cxxlcgi_USRLIBDIRS += \
${xde_USRLIBDIRS} \

########################################################################

#
# Executable .c sources
#
#cxxlcgi_EXE_C_SOURCES += \
#${XDE_SRC}/xde/base/Base.c \

#
# Executable .cc sources
#
#cxxlcgi_EXE_CC_SOURCES += \
#${XDE_SRC}/xde/base/Base.cc \

#
# Executable .cxx sources
#
cxxlcgi_EXE_CXX_SOURCES += \
${XDE_SRC}/capp/ccgi/cxxlcgi/ccxxlcgi.cxx \
${XDE_SRC}/capp/ccgi/cxxlcgi/ccxxlex.cxx \
${XDE_SRC}/capp/ccgi/cxxlcgi/ccxxlexer.cxx \
${XDE_SRC}/clib/ccgi/cgi.cxx \
${XDE_SRC}/clib/ccgi/ctemplatenamelist.cxx \
${XDE_SRC}/clib/ccgi/cdocumentnamelist.cxx \
${XDE_SRC}/clib/ccgi/ctemplatefilenameitems.cxx \
${XDE_SRC}/clib/ccgi/cdocumentfilenameitems.cxx \
${XDE_SRC}/clib/cyy/clexercgilex.cxx \
${XDE_SRC}/clib/cyy/clexersource.cxx \
${XDE_SRC}/clib/cyy/clexertoken.cxx \
${XDE_SRC}/clib/cyy/cyylexer.cxx \
${XDE_SRC}/clib/ct/ctfunctions.cxx \
${XDE_SRC}/clib/ct/ctfilefunctions.cxx \
${XDE_SRC}/clib/ct/ctdatefunctions.cxx \

#
# Executable .cpp sources
#
#cxxlcgi_EXE_CPP_SOURCES += \
#${XDE_SRC}/xde/base/Base.cpp \

#
# Executable .m sources
#
#cxxlcgi_EXE_M_SOURCES += \
#${XDE_SRC}/xde/base/Base.m \

#
# Executable .mm sources
#
#cxxlcgi_EXE_MM_SOURCES += \
#${XDE_SRC}/xde/base/Base.mm \


########################################################################

#
# Executable libraries
#
cxxlcgi_LIBS += \
${xde_LIBS}



