########################################################################
# Copyright (c) 1988-2018 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 11/16/2018
#
# generic Gcc Makefile for medusaxde Library libmedusaxde
########################################################################


#
# target
#
libmedusaxde_LIBTARGET = libmedusaxde.${LIBEXT}

########################################################################

#
# user c++ flags
#
libmedusaxde_USRCXXFLAGS += \
${medusaxde_USRCXXFLAGS} \

#
# user defines
#
libmedusaxde_USRDEFINES += \
${medusaxde_USRDEFINES} \

#
# user includes
#
libmedusaxde_USRINCLUDES += \
${medusaxde_USRINCLUDES} \

#
# user libdirs
#
libmedusaxde_USRLIBDIRS += \
${medusaxde_USRLIBDIRS} \

########################################################################

#
# Library .c sources
#
libmedusaxde_LIB_C_SOURCES += \

#
# Library .cc sources
#
#libmedusaxde_LIB_CC_SOURCES += \
#${MEDUSAXDE_SRC}/medusaxde/base/Base.cc \

#
# Library .cxx sources
#
libmedusaxde_LIB_CXX_SOURCES += \
${MEDUSAXDE_SRC}/clib/cxml/cxslt/cXslTransformer.cxx \
\
${XDE_SRC}/clib/cxsl/cxsltransformerinterface.cxx \
${XDE_SRC}/clib/cxsl/cxmlreaderinterface.cxx \
${XDE_SRC}/clib/cxsl/cxmlnodeinterface.cxx \
${XDE_SRC}/clib/cxsl/cxmlnodetype.cxx \

#
# Library .cpp sources
#
libmedusaxde_LIB_CPP_SOURCES += \
${MEDUSAXDE_SRC}/clib/clibc/clibxml2/clibxslt/cLibXsltXsltProcessorImplemented.cpp \
${MEDUSAXDE_SRC}/clib/clibc/clibxml2/clibxslt/cLibXsltXsltProcessor.cpp \
${MEDUSAXDE_SRC}/clib/clibc/clibxml2/clibxslt/cLibXsltXsltProcessorInterface.cpp \
${MEDUSAXDE_SRC}/clib/clibc/clibxml2/clibxslt/cLibXsltXsltParams.cpp \
${MEDUSAXDE_SRC}/clib/cxml/cxslt/cXsltProcessor.cpp \
${MEDUSAXDE_SRC}/clib/cxml/cxslt/cXsltProcessorInterface.cpp \
${MEDUSAXDE_SRC}/clib/cxml/cxslt/cXsltParams.cpp \
${MEDUSAXDE_SRC}/clib/cxml/cxslt/cXsltParamsInterface.cpp \
${MEDUSAXDE_SRC}/clib/cxml/cxslt/cXsltParam.cpp \
${MEDUSAXDE_SRC}/clib/cxml/cxslt/cXsltParamInterface.cpp \
${MEDUSAXDE_SRC}/clib/cxml/cXmlAttributeEncoder.cpp \
${MEDUSAXDE_SRC}/clib/cxml/cXmlTextEncoder.cpp \
${MEDUSAXDE_SRC}/clib/cos/cDebugInstance.cpp \
${MEDUSAXDE_SRC}/clib/cos/cDebug.cpp \
${MEDUSAXDE_SRC}/clib/cos/cDebugInterface.cpp \
${MEDUSAXDE_SRC}/clib/cbase/cBase.cpp \
\
${XDE_SRC}/clib/cos/cplatform/cplatform.cpp \
${XDE_SRC}/clib/cos/cplatform/cnamespace.cpp \

#
# Library .m sources
#
#libmedusaxde_LIB_M_SOURCES += \
#${MEDUSAXDE_SRC}/medusaxde/base/Base.m \

#
# Library .mm sources
#
#libmedusaxde_LIB_MM_SOURCES += \
#${MEDUSAXDE_SRC}/medusaxde/base/Base.mm \


########################################################################




